version: '3.6'

services:
    postgres_default:
        image: postgres:12.7
        environment:
          POSTGRES_PASSWORD: password
          PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
          - type: bind
            source: ./docker-compose-context/postgres_default/pgdata
            target: /var/lib/postgresql/data/pgdata
        expose:
          - "5432"
        ports:
          - "5432:5432"
        networks:
          - storage
                 

    # mssqlserver2019:
    #     image: "mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04"
    #     container_name: mssqlserver2019
    #     environment:
    #         SA_PASSWORD: "passw0rd"
    #         ACCEPT_EULA: "Y"
    #         MSSQL_DATA_DIR: /var/opt/sqlserver
    #         MSSQL_LOG_DIR: /var/opt/sqlserver
    #     volumes:
    #         - type: bind
    #           source: ./docker-compose-context/mssqlserver/volume_mssql
    #           target: /var/opt/mssql/data
    #         - type: bind
    #           source: ./docker-compose-context/mssqlserver/volume_user
    #           target: /var/opt/sqlserver
    #     expose:
    #         - "1433"
    #     ports:
    #         - "2433:1433"
            
    mongo_default:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: mongo
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - 27017:27017
        volumes:
          - type: bind
            source: ./docker-compose-context/mongo_default
            target: /data/db

    mongo_express_default:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
          ME_CONFIG_MONGODB_ADMINPASSWORD: password
          ME_CONFIG_MONGODB_SERVER: mongo
          #ME_CONFIG_MONGODB_ENABLE_ADMIN=: 'false'
          #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
          #ME_CONFIG_MONGODB_AUTH_USERNAME: mongo
          #ME_CONFIG_MONGODB_AUTH_PASSWORD: passw0rd

    azurite_default:
        image: "mcr.microsoft.com/azure-storage/azurite"
        logging:
            driver: none
        volumes:
            - type: bind
              source: ./docker-compose-context/azurite_default
              target: /data
        expose:
            - "20000"
            - "20001"
        ports: 
            - "20000:10000"
            - "20001:10001"
        networks:
            - storage

networks:
  storage:
      name: storage
      external: true
      driver: overlay